name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank You for pointing me to the issue - I wish You a great day."
        pr-message: "Thanks for helping me - I am still a novice with web-development and people like you help me to learn something and to reach new goals."
